
name: Release Automation using release-please
on:
    push:
      branches:
        - main  
permissions:
    contents: write
    pull-requests: write
jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
        - uses: google-github-actions/release-please-action@v3.7.10
          with:
            release-type: simple
            package-name: release-please-action
            token: ${{ secrets.RELEASE_PLEASE }}
